<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Agence OLJU</title>
        <link rel="stylesheet" href="../css/style.css">
    </head>
    <body>
         <header>
            
            <div class="logo"><img src="img/img/logo.png" alt="Agence OLJU"></div>
            <?php
            include_once 'menu.inc';
            ?>
        </header>
