<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Agence OLJU</title>
        <link rel="stylesheet" href="../css/style.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>
        <script src="../autres/pdf.js" defer></script>
    </head>
    <body>
         <header>
            
            <div class="logo"><img src="img/img/logo.png" alt="Agence OLJU"></div>
            <?php
            include_once 'menu.inc';
            ?>
        </header>
