<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Agence OLJU</title>
        <link rel="stylesheet" href="../css/style.css">
    </head>
    <body>
        <header>
        <div class="nav">
                <nav class="navLinks">
                    <a href="index.html" title="accueil">Accueil</a>
                    <a href="vuescontroleurs/formRechercheBien.php" title="recherche">Rechercher</a>
                    <a href="../vuescontroleurs/formConnexion.php" title="connexion">Connexion</a>
                    <a href="../contact.html" title="contact">Contact</a>
                </nav>
            </div>
        </header>
        <?php
        // put your code here
        ?>
    </body>
</html>
