<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        
        <footer>

            <div class="contactInfo">
                <h3>Nos coordonnées</h3>
                <p>10 Rue de la Lys, ROUBAIX 59100</p>
                <p>03 50 60 42 80</p>
                <p>OLJUAgence@gmail.com</p>
            </div>
            <div class="menuFooter">
                <h3>Parcourir</h3>
                <a href="index.html" title="accueil">Accueil</a>
                <a href="categorie/catmaison.html" title="maisons">Maisons</a>
                <a href="categorie/catappart.html" title="appartements">Appartements</a>
                <a href="categorie/catimmeuble.html" title="immeubles">Immeubles</a>
                <a href="categorie/catlocal.html" title="locaux">Locaux</a>
                <a href="categorie/catterrains.html" title="terrains">Terrains</a>
                <a href="contact.html" title="maisons">Contact</a>
            </div>
        </footer>
    </body>
</html>
